name: C/C++ CI

on:
  push:
    branches: [ root ]
  pull_request:
    branches: [ root ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: sudo apt install g++11 libstdc++11-dev
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"
    - uses: actions/checkout@v2
    - name: gcc version
      run: g++ -v
    - name: make test
      run: make test
