name: C/C++ CI

on:
  push:
    branches: [ root ]
  pull_request:
    branches: [ root ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install correct g++ version
      run: sudo apt install gcc-11 g++-11 && sudo update-alternatives --set g++ /usr/bin/g++-11
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"
    - uses: actions/checkout@v2
    - name: make test
      run: make test
