name: Release

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: MCJack123/ghaction-Generate-Release-Hashes@v2
      with:
        file-name: hashes.txt
        hash-type: sha256
    - uses: actions/upload-artifact@v2
      with:
        name: Asset Hashes
        path: hashes.txt
